// <auto-generated />
using System;
using ContactManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManagement.Api.Migrations
{
    [DbContext(typeof(ContactManagementDbContext))]
    [Migration("20250812223107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ContactManagement.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Contact_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Contact_Email");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Contact_Name");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Rue de la Paix, Paris",
                            CreatedAt = new DateTime(2025, 7, 13, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5486),
                            Email = "jean.dupont@email.com",
                            FirstName = "Jean",
                            LastName = "Dupont",
                            PhoneNumber = "0123456789",
                            UpdatedAt = new DateTime(2025, 7, 13, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5757)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Avenue des Champs, Lyon",
                            CreatedAt = new DateTime(2025, 7, 23, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5919),
                            Email = "marie.martin@email.com",
                            FirstName = "Marie",
                            LastName = "Martin",
                            PhoneNumber = "0987654321",
                            UpdatedAt = new DateTime(2025, 7, 23, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5921)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 2, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5924),
                            Email = "pierre.durand@email.com",
                            FirstName = "Pierre",
                            LastName = "Durand",
                            PhoneNumber = "0147258369",
                            UpdatedAt = new DateTime(2025, 8, 2, 22, 31, 7, 337, DateTimeKind.Utc).AddTicks(5925)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
